window.onload=function(){var b=f.zf();h=new Phaser.Game(b.width,b.height,Phaser.CANVAS);h.state.add("Boot",k);h.state.start("Boot")};var h,m,n,q,r,u;function v(b,a){if(!b)throw a;}
var w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},k=function(b){function a(){b.apply(this,arguments)}w(a,b);a.prototype.preload=function(){h.load.pack("preload","assets/assets-pack.json")};a.prototype.create=function(){h.input.maxPointers=1;h.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;h.scale.pageAlignHorizontally=!0;h.scale.pageAlignVertically=!0;n=f.Ff();h.state.add("Preload",
aa);f.va("Preload",!0)};return a}(Phaser.State),ba=function(){function b(a){this.level=a;this.Rb=!1;this.If=m.ability.global_cooldown}b.prototype.rc=function(){return!this.Rb};b.prototype.bd=function(){this.Rb||(this.Rb=!0,this.level.xa.Pc=!0,h.time.events.add(this.If,this.Ce,this))};b.prototype.Ce=function(){this.Rb=!1;this.level.xa.Pc=!1};return b}(),z=function(){function b(){this.y=this.x=0;this.Cc=[];this.Gd=!0;this.Yd=0;this.elements=h.add.group()}b.prototype.Xd=function(a){for(var e in this.Cc)if(f.Wd(a,
this.Cc[e]))return!0;return!1};b.prototype.qb=function(a,e,c,d,g,l){var p=y.ma.IMAGE;void 0===l&&(l=!0);this.Gd?this.Gd=!1:this.y+=b.spacing+this.Yd;a=this.Fe(p,this.x,this.y,e,c,a,d,g,l);this.Yd=a.height;return a};b.prototype.Fe=function(a,e,b,d,g,l,p,t,x){void 0===x&&(x=!0);a=new y(a,l,e,b,g,p,t,x);a.Sa(d,0);this.elements.add(a.group);this.Cc.push(new Phaser.Rectangle(a.x-a.width*d,a.y-0*a.height,a.width,a.height));return a};b.init=function(){b.spacing=b.fa(b.Xa)};b.Pb=function(a){return Math.round(h.world.width*
a/100)};b.fa=function(a){return Math.round(h.world.height*a/100)};b.ra=function(a,e){var c=b.fa(e);a.width=Math.round(a.width*c/a.height);a.height=c};b.eh=function(a,e){var c=b.Pb(e),d=Math.round(a.height*c/a.width);a.width=c;a.height=d};b.Vc=function(a,e){a.width=Math.round(a.width*e/a.height);a.height=e};b.spacing=30;b.Xa=5;return b}(),Entity=function(){function b(a,e,b,d,g,l,p,t,x,H){void 0===H&&(H=!1);this.map=a;this.controller=e;this.aa=b;this.pe=d;this.zg=g;this.Eg=t;this.Re=x;this.Pg=H;this.selected=
this.alive=!1;this.$b=null;this.group=h.add.group();this.sprite=f.addSprite(0,0,l,p);this.sprite.width=A.pb*g;this.sprite.height=A.pb*g;this.sprite.anchor.setTo(.5,.5);h.physics.enable(this.sprite,Phaser.Physics.ARCADE);this.group.addChild(this.sprite);this.Cd(b);this.cursor=h.add.graphics(0,0);this.cursor.visible=!1;a=Math.max(A.Ae,Math.sqrt(Math.pow(this.sprite.width,2)+Math.pow(this.sprite.height,2)));this.cursor.lineStyle(z.fa(.7),16777215,1);this.cursor.drawCircle(0,0,a);this.group.addAt(this.cursor,
0);this.Eg&&(this.sprite.inputEnabled=!0,this.sprite.events.onInputUp.add(function(){this.alive&&this.controller.select(this)},this))}b.prototype.Cd=function(a){null!=this.aa&&this.ga(!1);this.aa=a;null!=a&&(this.group.x=a.na.center.x,this.group.y=a.na.center.y);null!=this.aa&&this.ga(!0)};b.prototype.ga=function(a){var e=[];null!=this.aa&&e.push(this.aa.ha);1<this.pe&&(e=e.concat(this.aa.ha.Kd(1,Math.max(1,Math.floor(this.pe/2)))));var b,d=[],g;for(g in e)b=this.map.Ia(e[g]),null!=b&&(a?b.mc(this):
b.gc(this),this.Re||d.push(b));this.map.vg(d)};b.prototype.Zc=function(){this.alive=!0};b.prototype.destroy=function(){this.ga(!1);this.alive=!1;this.controller.jf(this)};b.prototype.Lc=function(){return this.selected};b.prototype.Ta=function(a){this.selected=a;this.cursor.visible=a};b.prototype.Fc=function(){return this.$b=null!=this.aa?new Phaser.Rectangle(this.aa.na.center.x-this.sprite.width/2,this.aa.na.center.y-this.sprite.height/2,this.sprite.width,this.sprite.height):null};b.prototype.toString=
function(){return"Entity at Cell "+this.aa};return b}(),B=function(){function b(a,e,b,d,g,l){this.level=a;this.gameManager=e;this.sd=d;this.rd=g;this.context=l;this.background=h.add.graphics(0,0);this.background.beginFill(0,.7);this.background.drawRect(0,0,h.world.width,h.world.height);this.background.inputEnabled=!0;this.message=h.add.text(h.world.centerX,h.world.centerY-z.spacing,b,{font:"bold "+z.fa(15)+"px Arial",fill:"#f2f2f2"});this.message.anchor.setTo(.5,1);z.ra(this.message,15);this.yd=new y(y.ma.IMAGE,
"button_yes",h.world.centerX-z.spacing/2,h.world.centerY,18,this.Wg,this);this.yd.Sa(1,0);this.xd=new y(y.ma.IMAGE,"button_no",h.world.centerX+z.spacing/2,h.world.centerY,18,this.Qf,this);this.xd.Sa(0,0);this.elements=[this.background,this.message,this.yd.group,this.xd.group];this.hide()}b.prototype.hide=function(){this.gameManager.isPaused=!1;this.elements.forEach(function(a){a.visible=!1},this)};b.prototype.show=function(){this.gameManager.isPaused=!0;this.elements.forEach(function(a){a.visible=
!0},this);this.level.Nb()};b.prototype.Wg=function(){this.hide();null!=this.sd&&this.sd.apply(this.context)};b.prototype.Qf=function(){this.hide();null!=this.rd&&this.rd.apply(this.context)};return b}(),ca=function(){function b(){this.all=[];this.Ca=0;this.load()}b.prototype.add=function(a){var e=new C(-1,a,q,new Date);this.all.push(e);this.all.sort(this.Ag);this.all.sort(this.Bg);this.Ng();a>this.Ca&&(this.Ca=a);this.save()};b.prototype.getTop=function(){var a;a=Math.min(this.all.length,10);for(var e=
[],b=0;b<a;b++)e[b]=this.all[b].toArray();return e};b.prototype.reset=function(){this.all=[];this.Ca=0;this.save()};b.prototype.Bg=function(a,e){return a.points>e.points?-1:1};b.prototype.Ag=function(a,e){return a.date.getTime()<e.date.getTime()?1:-1};b.prototype.Ng=function(){for(var a=0;a<this.all.length;a++)this.all[a].fc=a+1};b.prototype.save=function(){for(var a,e=[],b=0;b<this.all.length;b++)a=this.all[b].Ef(),e.push(a);a=JSON.stringify(e);localStorage.setItem("scoresDatas-all",a);localStorage.setItem("scoresDatas-bestScore",
JSON.stringify(this.Ca))};b.prototype.load=function(){this.all=[];var a=localStorage.getItem("scoresDatas-all");if(null!=a)for(var a=JSON.parse(a),e,b=0;b<a.length;b++)e=new C,e.ug(a[b]),this.all.push(e);this.Ca=0;a=localStorage.getItem("scoresDatas-bestScore");null!=a&&(this.Ca=JSON.parse(a))};return b}(),D=function(){function b(a){this.group=a;this.sounds={};var e=b.config[a];v(e instanceof Object,"Sound Group with key '"+a+"' not found");var c,d,g;for(g in e)a=e[g],c=a.key,d=a.loop,void 0===d&&
(d=!1),this.sounds[c]=h.add.audio(c,a.volume,d)}b.init=function(){this.config=h.cache.getJSON("sounds_config")};b.prototype.play=function(a){this.getSound(a).play()};b.prototype.volume=function(a,e){this.getSound(a).volume=e*this.xf(a)};b.prototype.xf=function(a){var e=b.config[this.group],c;for(c in e)if(e[c].key==a)return e[c].volume;console.warn("Default volume '"+a+"' in group '"+this.group+"' not found");return 1};b.prototype.stop=function(a){this.getSound(a).stop()};b.prototype.stopAll=function(){for(var a in this.sounds)this.sounds[a].stop()};
b.prototype.getSound=function(a){var e=this.sounds[a];v(e instanceof Phaser.Sound,"Sound with key '"+a+"' not found in group '"+this.group+"'");return e};return b}(),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},J=function(b){function a(a,c,d,g){b.call(this,c,d,g,m.predator.sizecells,m.predator.sizesprite,"predator",!1,!1,!1);this.level=a;this.yb=this.yc=!1;this.rotation=
0;this.ya=this.Tc=this.ba=this.pa=null;this.bc=this.cc=this.Kc=!1;this.cb=this.bb=this.ib=this.kc=null;this.Zc();this.range=m.predator.range;this.gd=m.predator.waterneeded;this.Ya=new ba(a);this.ag=m.predator.plantrange;this.map.wg(g.ha,this.ag);this.Ob=new da(this);this.health=m.predator.health;this.za=m.predator.hydration;this.La=m.predator.hunger;this.Ja=m.predator.energy;this.Ra=m.predator.seeds;a=Math.ceil(1E3/(m.predator.openmouthtime/6));c=Math.ceil(1E3/(m.predator.closemouthtime/6));this.sprite.animations.add("open_mouth",
[0,1,2,3,4,5],a,!1);this.sprite.animations.add("close_mouth",[5,4,3,2,1,0],c,!1);this.wa=f.addSprite(0,0,"waterjet");h.physics.enable(this.wa,Phaser.Physics.ARCADE);this.wa.anchor.setTo(1,.5);z.Vc(this.wa,A.pb*m.predator.sizewaterjet);this.wa.visible=!1;this.Qg=m.predator.waterjettime;this.oa=f.addSprite(0,0,"tongue");h.physics.enable(this.oa,Phaser.Physics.ARCADE);this.oa.anchor.setTo(0,.5);this.Mg=this.oa.width;z.Vc(this.oa,A.pb*m.predator.sizetongue);this.oa.width=0;4;this.se=m.predator.tonguegrabtime;
this.seed=f.addSprite(0,0,"seed_green");this.seed.anchor.setTo(.5,.5);z.Vc(this.seed,A.pb*m.predator.sizeseed);this.seed.alpha=0;this.qg=m.predator.seedlaunchtime;this.group.addAt(this.oa,0);this.Bd=Phaser.Timer.SECOND*m.predator.time_dehydrate;a=Phaser.Timer.SECOND*m.predator.time_hunger;c=Phaser.Timer.SECOND*m.predator.time_energy;d=Phaser.Timer.SECOND*m.predator.time_seeds;this.sg=Phaser.Timer.SECOND*m.predator.time_selfheal;this.bf=Phaser.Timer.SECOND*m.predator.time_deteriorate;this.ff=Phaser.Timer.SECOND*
m.predator.time_drinking;this.sa=h.time.events.loop(this.Bd,this.Ad,this);this.Rd=h.time.events.loop(a,this.$e,this);this.Ed=h.time.events.loop(c,this.Ze,this);h.time.events.loop(d,this.eg,this);this.ad();this.sounds=new D("predator")}w(a,b);a.prototype.update=function(){this.group.rotation=this.rotation};a.prototype.kill=function(){this.sounds.stopAll();this.sounds.play("death");null!=this.sa&&(this.sa.timer.remove(this.sa),this.sa=null);this.Rd.timer.remove(this.Rd);this.Ed.timer.remove(this.Ed);
this.sprite.loadTexture("images-atlas","predator_dead");this.oa.alpha=0;this.Ob.closed=!0;h.camera.shake(.01,200);this.destroy()};a.prototype.yg=function(a){this.Tc=this.ba;a instanceof A?this.pa=a:a instanceof Entity?this.ba=a:this.ba=this.pa=null;this.bc||this.xb()};a.prototype.tb=function(){return null!=this.ba&&this.aa.ha.distance(this.ba.aa.ha)<=this.range};a.prototype.Bc=function(){if(this.Ya.rc()&&null!=this.ba){var a=!1;if(this.ba instanceof E)this.ba.ca>E.Ha.WATERED&&(a=!0);else if(this.ba instanceof
F&&this.tb()||this.ba instanceof G&&this.tb()&&!this.yb)a=!0;a&&(this.Ya.bd(),this.Jg())}};a.prototype.Jg=function(){if(null!=this.ba){this.ba instanceof F&&(this.ba.freeze=!0);this.Qc();var a=f.yf(this.oa.world,this.ba.group.position);this.Qb=h.add.tween(this.oa).to({width:a},this.se);this.Qb.onComplete.add(this.Kg,this);this.Qb.start();this.sounds.play("tongue_launch")}};a.prototype.Kg=function(){this.sounds.stop("tongue_launch");if(null!=this.ba)if(this.ba instanceof G&&null==this.cb)this.yb=!0,
this.cb=h.time.events.loop(this.ff,this.ef,this),this.sounds.play("drop_inwater"),this.sounds.play("swallowing_water");else if(this.ba instanceof E||this.ba instanceof F){if(this.ba instanceof F){var a=this.ba;a.jb(!0);a.Ua()}this.oa.addChild(this.ba.group);this.ba.group.position.x=this.Mg;this.ba.group.position.y=0;this.Kc=!0;this.ya=this.ba;this.level.select(null);this.sounds.play("tongue_stick")}};a.prototype.ef=function(){null!=this.sa&&(this.sa.timer.remove(this.sa),this.sa=null);this.tc(1)};
a.prototype.Fg=function(){null!=this.cb&&(this.cb.timer.remove(this.cb),this.cb=null,this.sounds.stop("swallowing_water"));this.yb=!1;this.xb();null==this.sa&&(this.sa=h.time.events.loop(this.Bd,this.Ad,this))};a.prototype.Qc=function(){this.cc||(this.od(!0),this.cc=!0)};a.prototype.od=function(a){var b,d;b=this.sprite.animations;d=b.currentAnim;null!=d&&d.isPlaying?d.onComplete.addOnce(function(){b.play(a?"open_mouth":"close_mouth")}):b.play(a?"open_mouth":"close_mouth")};a.prototype.xb=function(){!this.bc&&
this.cc&&(this.bc=!0,this.yb&&this.Fg(),null!=this.Qb&&(this.Qb.stop(),this.Qb=null),null==this.jc&&(this.jc=h.add.tween(this.oa).to({width:1},this.se),this.jc.onComplete.add(this.Lg,this),this.jc.start(),null!=this.Tc&&this.Tc instanceof G&&this.sounds.play("water_drop")),this.cc=!1)};a.prototype.Lg=function(){this.jc=null;this.od(!1);!this.Kc||null==this.ya||this.ya instanceof G||(this.digest(),this.sounds.play("monster_bite"));this.bc=!1};a.prototype.digest=function(){if(null!=this.ya){if(this.ya instanceof
F){this.vb(m.predator.eat_prey_hunger);var a=this.ya;this.oa.removeChild(a.group);h.world.addChild(a.group);a.kill()}else this.ya instanceof E&&(a=this.ya,a.ca==E.Ha.LEAFY?(this.vb(m.predator.eat_plantleafy_hunger),this.wb(m.predator.eat_plantleafy_seeds)):a.ca==E.Ha.FRUITY?(this.vb(m.predator.eat_plantfruity_hunger),this.sc(m.predator.eat_plantfruity_energy),this.wb(m.predator.eat_plantfruity_seeds)):a.ca==E.Ha.SEEDY&&(this.vb(m.predator.eat_plantseedy_hunger),this.sc(m.predator.eat_plantseedy_energy),
this.wb(m.predator.eat_plantseedy_seeds)),this.oa.removeChild(a.group),h.world.addChild(a.group),a.kill());this.Kc=!1;this.ya=null}};a.prototype.qc=function(){return this.alive&&0<this.Ra&&null!=this.pa&&this.pa.isEmpty()};a.prototype.plant=function(){if(this.Ya.rc()&&this.qc()){this.Ya.bd();this.Qc();this.ce=this.controller.wc(this.pa);this.seed.position=this.group.position.clone();this.seed.alpha=1;this.seed.rotation=f.Zb();var a=this.ce.group.position.clone();this.me=h.add.tween(this.seed).to({x:a.x,
y:a.y},this.qg);this.me.onComplete.add(this.rg,this);this.me.start();this.sounds.play("spit");this.wb(-1);this.xb()}};a.prototype.rg=function(){this.sounds.play("dirt_hit");this.xb();this.seed.alpha=0;this.ce.Pe()};a.prototype.ed=function(){if(this.Ya.rc()&&null!=this.ba&&this.ba instanceof E){var a=this.ba;this.za>=this.gd&&a.ca==E.Ha.SEED&&(this.Ya.bd(),this.Qc(),this.tc(-this.gd),this.wa.position=this.group.position.clone(),this.wa.rotation=this.group.rotation,this.wa.visible=!0,this.kc=a,a=a.group.position.clone(),
a=h.add.tween(this.wa).to({x:a.x,y:a.y},this.Qg),a.onComplete.add(this.Rg,this),a.start(),this.sounds.play("water_throw"))}};a.prototype.Rg=function(){null!=this.kc&&(this.xb(),this.kc.ed(),this.kc=null,this.wa.visible=!1)};a.prototype.Qe=function(){return this.za>=this.gd};a.prototype.heal=function(){this.wd(1)};a.prototype.wd=function(a){var b=Math.max(0,Math.min(m.predator.health,this.health+a));b!=this.health&&(this.health=b,this.controller.Cb(I.Wa.HEALTH,this.health,a))};a.prototype.Ad=function(){this.tc(-1)};
a.prototype.tc=function(a){var b=Math.max(0,Math.min(m.predator.hydration,this.za+a));b!=this.za&&(this.za=b,this.controller.Cb(I.Wa.HYDRATION,this.za,a),this.ad())};a.prototype.$e=function(){this.vb(-1)};a.prototype.vb=function(a){var b=Math.max(0,Math.min(m.predator.hunger,this.La+a));b!=this.La&&(this.La=b,this.controller.Cb(I.Wa.HUNGER,this.La,a),this.ad())};a.prototype.Ze=function(){this.sc(-1)};a.prototype.sc=function(a){var b=Math.max(0,Math.min(m.predator.energy,this.Ja+a));b!=this.Ja&&(this.Ja=
b,this.controller.Cb(I.Wa.ENERGY,this.Ja,a))};a.prototype.eg=function(){this.alive&&0<this.za&&0<this.La&&0<this.Ja&&this.wb(1)};a.prototype.wb=function(a){var b=Math.max(0,this.Ra+a);b!=this.Ra&&(b>this.Ra&&this.sounds.play("seed_gained"),this.Ra=b,this.controller.Cb(I.Wa.SEEDS,this.Ra,a))};a.prototype.ad=function(){(this.yc=0>=this.za||0>=this.La)?(null==this.bb&&(this.bb=h.time.events.loop(this.bf,this.af,this)),null!=this.ib&&(this.ib.timer.remove(this.ib),this.ib=null)):(null!=this.bb&&(this.bb.timer.remove(this.bb),
this.bb=null,this.sounds.stop("predator_pain")),null==this.ib&&(this.ib=h.time.events.loop(this.sg,this.heal,this)))};a.prototype.af=function(){this.alive&&this.yc&&0<this.health&&(this.wd(-1),h.time.events.add(f.Da(0,300,!0),function(){this.sounds.stop("predator_pain");this.sounds.volume("predator_pain",f.Da(.5,1.5,!1));this.sounds.play("predator_pain")},this),0>=this.health&&this.kill())};return a}(Entity),fa=function(){function b(a){this.id=a;this.links=[]}b.prototype.dc=function(a,e){this.links.push(new ea(this,
a,e))};b.prototype.Ge=function(a){this.links.push(a)};b.prototype.Gc=function(){var a=[],e;for(e in this.links)a.push(this.links[e].Nc.id);return a};b.prototype.Af=function(a){var e,b;for(b in this.links)if(e=this.links[b],e.Nc.id==a)return e;throw"Neighbor with id '"+a+"' can't be found in neighbors of Node with id '"+this.id+"'";};b.prototype.Db=function(a){return this.Af(a).weight};b.prototype.clone=function(){var a=new b(this.id),e;for(e in this.links)a.Ge(this.links[e].clone());return a};return b}(),
w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},ga=function(b){function a(){b.apply(this,arguments)}w(a,b);a.prototype.create=function(){new y(y.ma.IMAGE,"button_back",z.spacing,z.spacing,14,this.back,this);var a=h.add.text(h.world.centerX,z.spacing,n.scores.title_text,{font:"bold "+z.fa(12)+"px Arial",fill:"#471c07",align:"center"});a.anchor.setTo(.5,0);z.ra(a,12);
var b=z.Pb(17),d=n.scores.tab_headings,a=a.y+a.height+z.spacing,g=h.add.text(h.world.centerX,a,"",{font:"bold "+z.fa(6)+"px Arial",fill:"#000000",align:"left",tabs:[110*b/100,115*b/100,125*b/100]});g.anchor.setTo(.5,0);g.parseList(d);b=h.add.text(h.world.centerX,a+g.height,n.scores.tab_list_empty,{font:z.fa(5)+"px Arial",fill:"#000000",align:"center",tabs:[90*b/100,105*b/100,90*b/100]});b.anchor.setTo(.5,0);0<r.all.length&&b.parseList(r.getTop());(new y(y.ma.TEXT,String(n.scores.reset),h.world.width-
z.spacing,z.spacing,14,this.lg,this)).Sa(1,0)};a.prototype.back=function(){f.va("Menu")};a.prototype.lg=function(){r.reset();f.va("Scores")};return a}(Phaser.State),ha=function(){function b(){this.Ug=z.Pb(15);this.Xg=z.fa(5);this.Yg=z.spacing;this.ja=[];this.font="bold "+z.fa(5)+"px Arial"}b.prototype.clear=function(){this.ja=[]};b.prototype.addText=function(a,b){this.ja.push([a,b])};b.prototype.show=function(){var a,b;for(b in this.ja)a=this.ja[b][0]+": "+this.ja[b][1],h.debug.text(a,this.Ug,this.Xg+
Number(b)*this.Yg,"#FFFFFF",this.font)};return b}(),ja=function(){function b(a,b,c){this.level=a;this.map=b;this.controller=c;this.Ba=[];this.xc=this.ld=null;this.o=new J(a,b,c,b.center);this.he=m.consumermanager.preys_adding_min;this.gb=this.ge=m.consumermanager.preys_adding_init;this.cg=m.consumermanager.preys_adding_dec;this.dg=m.consumermanager.preys_adding_deceach;this.Pa=new ia(this.map)}b.prototype.init=function(a){this.qa=a;for(a=0;a<m.consumermanager.preys_max;a++)this.Xe()};b.prototype.start=
function(){this.gb=this.ge;this.ld=h.time.events.loop(this.gb,this.kd,this);this.kd();this.xc=h.time.events.loop(this.dg,this.Ye,this)};b.prototype.end=function(){for(var a in this.Ba)this.Ba[a].kill()};b.prototype.update=function(){this.o.update();for(var a in this.Ba)this.Ba[a].update();this.o.Ob.update()};b.prototype.Xe=function(){this.Ba.push(new F(this.level,this.map,this.controller,this,this.qa,null,this.Pa))};b.prototype.kd=function(){for(var a=null,b=0;b<this.Ba.length;b++){var c=this.Ba[b];
if(!c.alive){a=c;break}}null!=a&&(b=this.map.Cf(),a.Cd(b),a.jg())};b.prototype.Ye=function(){this.gb=Math.max(this.he,this.gb-this.cg);this.ld.delay=this.gb;this.gb<=this.he&&this.xc.timer.remove(this.xc)};return b}(),ka=function(){function b(a){this.level=a;this.Vb=!1}b.prototype.init=function(a,b,c,d){this.gameManager=a;this.qa=b;this.j=c;this.Ka=d};b.prototype.select=function(a){this.Hb()&&this.level.select(a)};b.prototype.ve=function(){this.Hb()&&this.level.select(null)};b.prototype.Hb=function(){return this.Vb?
this.Vb=!1:!0};b.prototype.$c=function(){this.Hb()&&null!=this.level.selection&&this.j.o.Bc()};b.prototype.plant=function(){this.Hb()&&this.j.o.qc()&&this.j.o.plant()};b.prototype.wc=function(a){return this.qa.wc(a)};b.prototype.fd=function(){this.Hb()&&null!=this.level.selection&&this.level.selection instanceof E&&this.j.o.ed()};b.prototype.$f=function(a){var b=this.level.selection;null!=b&&b instanceof A&&b.vc(a)&&this.level.select(a)};b.prototype.Cb=function(a,b,c){this.Ka.update(a,b,c)};b.prototype.jf=
function(a){this.level.selection==a&&this.select(null);a instanceof J&&this.gameManager.end()};return b}(),C=function(){function b(a,b,c,d){this.fc=a;this.points=b;this.Sc=c;this.date=d}b.prototype.toArray=function(){return[this.fc,this.points,this.Sc,this.date.toLocaleDateString()]};b.prototype.Ef=function(){return[this.fc,this.points,this.Sc,this.date.getTime()]};b.prototype.ug=function(a){this.fc=a[0];this.points=a[1];this.Sc=a[2];this.date=new Date(a[3])};return b}(),K,L=K||(K={});
L[L.SEARCHFOOD=0]="SEARCHFOOD";L[L.COMETOFOOD=1]="COMETOFOOD";L[L.EATFOOD=2]="EATFOOD";L[L.FLEE=3]="FLEE";var M,N=M||(M={});N[N.SEARCH=0]="SEARCH";N[N.COME=1]="COME";N[N.FLEE=2]="FLEE";
var ma=function(){function b(a,b,c,d,g,l){this.level=a;this.map=b;this.j=c;this.qa=d;this.ea=g;this.Pa=l;this.state=K.SEARCHFOOD;this.Oa=-1;this.ia=null;this.ic=!1;this.init();this.Ig=m.artificialintelligence.threateneddist;this.sf=m.artificialintelligence.fleedistance_min;this.rf=m.artificialintelligence.fleedistance_max}b.prototype.init=function(){this.state=K.SEARCHFOOD;this.ia=null;this.ic=!1;this.Oa=-1};b.prototype.kb=function(){!this.ic&&null!=this.ea&&this.ea.alive&&(this.ic=!0,this.Je(),this.Ee(),
this.ic=!1)};b.prototype.Je=function(){null==this.ia||this.ia.alive||(this.ia=null);this.state!=K.FLEE&&this.Mf()&&(this.state=K.FLEE,this.ea.qf());switch(this.state){case K.SEARCHFOOD:this.ia=this.qa.wf(this.ea);null!=this.ia&&(this.state=K.COMETOFOOD);break;case K.COMETOFOOD:null==this.ia?this.state=K.SEARCHFOOD:this.ea.Vd(this.ia)&&(this.state=K.EATFOOD);break;case K.EATFOOD:null==this.ia&&(this.state=K.SEARCHFOOD,this.ea.Ua());break;case K.FLEE:this.ea.aa.ha.distance(this.j.o.aa.ha)>=this.Hd&&
(this.state=K.SEARCHFOOD)}};b.prototype.Mf=function(){var a=this.j.o.group,b=f.Dc(a,this.ea.group),a=f.vf(a.rotation,b)<this.j.o.Ob.halfWidth,b=(this.ea.isMoving?this.ea.Aa:this.ea.aa).ha.distance(this.j.o.aa.ha);return this.j.o.alive&&a&&b<=this.Ig};b.prototype.Ee=function(){var a;switch(this.state){case K.SEARCHFOOD:this.ea.isMoving&&this.Oa==M.SEARCH||(a=this.level.map.Df(),this.move(a,!1),this.Oa=M.SEARCH);break;case K.COMETOFOOD:this.ea.isMoving&&this.Oa==M.COME||null==this.ia||(a=this.ia.aa,
this.move(a,!1),this.Oa=M.COME);break;case K.EATFOOD:null!=this.ia&&this.ia.alive&&!this.ea.Wb&&this.ea.Vd(this.ia)&&this.ea.Bc(this.ia);break;case K.FLEE:if(!this.ea.isMoving||this.Oa!=M.FLEE){this.Hd=f.Da(this.sf,this.rf+1,!0);a=this.level.map.Hc(this.ea.aa,this.Hd,!0);var b=[],c,d=-1,g;for(g in a)c=a[g].ha.distance(this.j.o.aa.ha),c>d&&(b=[],d=c),c>=d&&b.push(a[g]);0<b.length&&(a=b[f.Da(0,b.length,!0)],this.move(a,!0),this.Oa=M.FLEE)}}};b.prototype.move=function(a,b){var c=this.Pa.find(this.ea.isMoving?
this.ea.Aa:this.ea.aa,a,this.ea);null!==c&&this.ea.tf(c,b)};b.pc=K;b.Tb=M;return b}(),na=function(){function b(a,b,c,d,g,l){this.level=a;this.controller=b;this.map=c;this.gameManager=d;this.Bb=g;this.xa=l;this.Gb=!1;this.fb=null;this.Fb=this.isDragging=this.ac=this.de=this.Oc=!1;this.Va=null;h.input.enabled=!0;h.input.onDown.add(this.onDown,this);h.input.onUp.add(this.onUp,this);h.input.addMoveCallback(this.Vf,this)}b.prototype.onDown=function(){this.gameManager.isPaused||(this.Fb=this.isDragging=
this.ac=!1,this.fb=h.input.activePointer.position.clone(),this.de=null!=this.level.selection&&null!=this.level.selection.Fc()&&f.Wd(this.fb,this.level.selection.Fc()),this.Gb=this.Bb.Xd(this.fb)||this.xa.Xd(this.fb),this.Oc=!0)};b.prototype.Vf=function(){!this.gameManager.isPaused&&h.input.activePointer.isDown&&(null!=this.Va||this.Fb||(this.Va=h.time.events.add(300,this.Wf,this)),this.ac&&!this.Fb&&this.Tf())};b.prototype.Wf=function(){this.gameManager.isPaused||(this.Va=null,this.ac=!0)};b.prototype.Tf=
function(){this.gameManager.isPaused||(this.isDragging=this.Fb=!0,!this.Gb&&this.level.selection instanceof A&&this.level.selection.Ta(!1))};b.prototype.onUp=function(){this.gameManager.isPaused||(null!=this.Va&&(this.Va.timer.remove(this.Va),this.Va=null),this.isDragging?(this.Fb=this.isDragging=this.ac=!1,this.controller.Vb=!0):(this.controller.Vb=!1,this.Gb||null==this.fb||this.controller.select(this.map.xg(this.fb))),this.Gb=this.Oc=!1)};return b}(),w=this&&this.la||function(b,a){function e(){this.constructor=
b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},O,P=O||(O={});P[P.UNBORN=0]="UNBORN";P[P.SEED=1]="SEED";P[P.WATERED=2]="WATERED";P[P.LEAFY=3]="LEAFY";P[P.FRUITY=4]="FRUITY";P[P.SEEDY=5]="SEEDY";
var E=function(b){function a(a,c,d,g){b.call(this,c,d,g,m.plant.sizecells,m.plant.sizesprite,"plant_green",!1,!0,!0,!0);this.level=a;this.ca=O.UNBORN;this.nb=this.lb=this.mb=null;this.group.rotation=f.Zb();this.group.alpha=0;this.Od=Phaser.Timer.SECOND*m.plant.growtime_leaf;this.Nd=Phaser.Timer.SECOND*m.plant.growtime_fruit;this.Pd=Phaser.Timer.SECOND*m.plant.growtime_seed;this.sounds=new D("plant")}w(a,b);a.prototype.Pe=function(){this.alive||(this.Zc(),this.ca=O.SEED,this.group.alpha=1,this.controller.$f(this))};
a.prototype.kill=function(){this.alive&&(this.ca=O.UNBORN,this.group.alpha=0,this.qe(),this.destroy())};a.prototype.ed=function(){this.ca==O.SEED&&(this.ca=O.WATERED,this.sprite.frame=1,this.mb=h.time.events.add(this.Od,this.$d,this))};a.prototype.$d=function(){this.ca==O.WATERED&&(this.ca=O.LEAFY,this.sprite.frame=2,this.sounds.play("plant_growing"),this.lb=h.time.events.add(this.Nd,this.Id,this))};a.prototype.Id=function(){this.ca==O.LEAFY&&(this.ca=O.FRUITY,this.sprite.frame=3,this.sounds.play("plant_growing"),
this.nb=h.time.events.add(this.Pd,this.seed,this))};a.prototype.seed=function(){this.ca==O.FRUITY&&(this.ca=O.SEEDY,this.sprite.frame=4,this.sounds.play("plant_growing"))};a.prototype.Ud=function(){return this.ca>O.WATERED};a.prototype.cf=function(){this.qe();this.ca==O.LEAFY?this.ca=O.UNBORN:this.ca--;this.ca<=O.UNBORN?this.kill():this.sprite.frame=this.ca-1;switch(this.ca){case O.WATERED:this.mb=h.time.events.add(this.Od,this.$d,this);break;case O.LEAFY:this.lb=h.time.events.add(this.Nd,this.Id,
this);break;case O.FRUITY:this.nb=h.time.events.add(this.Pd,this.seed,this)}};a.prototype.qe=function(){null!=this.mb&&(this.mb.timer.remove(this.mb),this.mb=null);null!=this.lb&&(this.lb.timer.remove(this.lb),this.lb=null);null!=this.nb&&(this.nb.timer.remove(this.nb),this.nb=null)};a.Ha=O;return a}(Entity),oa=function(){function b(){}b.init=function(){b.bh=Phaser.Math.degToRad(90);b.ah=Phaser.Math.degToRad(180)};b.Ac=function(a,b,c,d){var g=new Phaser.Point(0,0),l;l=Math.sqrt(Math.pow(Math.abs(a.x-
b.x),2)+Math.pow(Math.abs(a.y-b.y),2));g.x=b.x+d/l*(Math.cos(c)*(a.x-b.x)-Math.sin(c)*(a.y-b.y));g.y=b.y+d/l*(Math.sin(c)*(a.x-b.x)+Math.cos(c)*(a.y-b.y));return g};return b}(),da=function(){function b(a){this.o=a;this.lc=m.sightfog.activated;this.closed=!1;this.minWidth=m.sightfog.min_width;this.maxWidth=m.sightfog.max_width;this.Sg=this.maxWidth-this.minWidth;this.halfWidth=1;this.eb=this.lc?h.add.graphics(0,0):null}b.prototype.update=function(){if(this.lc){var a,b,c;a=f.Gf(this.o.group.position,
this.o.group.width/4,this.o.group.rotation+Math.PI);this.eb.clear();this.eb.beginFill(0);this.closed?this.eb.drawCircle(a.x,a.y,2*h.world.width):(this.halfWidth=(this.Sg*this.o.Ja/100+this.minWidth)/2,b=this.o.group.rotation-this.halfWidth,c=this.o.group.rotation+this.halfWidth,this.eb.arc(a.x,a.y,h.world.width,b,c,!0));this.eb.endFill()}};return b}(),f=function(){function b(){}b.va=function(a,b){void 0===b&&(b=!1);b&&(Q.init(),Q.show());h.time.events.add(b?100:0,function(a){h.state.start(a)},this,
a)};b.Ff=function(){var a="strings_en";b.Tb()&&(a="strings_fr");return h.cache.getJSON(a)};b.addSprite=function(a,b,c,d){void 0===d&&(d=!0);return d?h.add.sprite(a,b,"images-atlas",c):h.add.sprite(a,b,c)};b.zf=function(){var a=window.innerHeight,b=window.innerWidth,c=9*b/16;c>a&&(c=a,b=16*c/9);return{width:b,height:c}};b.Tb=function(){return"FR"===(window.navigator.userLanguage||window.navigator.language).substring(0,2).toUpperCase()};b.pc=function(){return(new Date).getTime()};b.fe=function(a){return 0>
a?2*Math.PI+a:a};b.dh=function(a){return a>Math.PI?a-2*Math.PI:a};b.Zb=function(){return this.Da(-Math.PI,Math.PI)};b.yf=function(a,b){return h.physics.arcade.distanceBetween(a,b)};b.Dc=function(a,b){return h.physics.arcade.angleBetween(a,b)};b.vf=function(a,b){var c=Math.abs(this.fe(a)-this.fe(b));return Math.min(c,2*Math.PI-c)};b.Gf=function(a,b,c){return new Phaser.Point(a.x+b*Math.cos(c),a.y+b*Math.sin(c))};b.Wd=function(a,b){return b.contains(a.x,a.y)};b.Da=function(a,b,c){a=Math.random()*(b-
a)+a;void 0==c&&(c=!1);c&&(a=Math.round(a),a==b&&a--);return a};b.Zg=function(a,b,c){return Math.max(b,Math.min(c,a))};b.$g=function(a,b,c){void 0===c&&(c=null);for(var d=[],g,l=0;l<b;l++){g=[];for(var p=0;p<a;p++)g.push(c);d.push(g)}return d};b.shuffle=function(a){for(var e,c,d=0;10>d;d++)for(var g=0;g<a.length;g++)e=b.Da(0,a.length,!0),c=a[e],a[e]=a[g],a[g]=c;return a};b.inArray=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};b.clone=function(a){return a.slice()};return b}(),w=this&&
this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},pa=function(b){function a(a,c,d){b.call(this,a,c,d,m.palmtree.sizecells,m.palmtree.sizesprite,"palmtree",!0,!1,!1);this.group.rotation=f.Zb()}w(a,b);return a}(Entity),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=
a.prototype,new e)},qa=function(b){function a(){b.apply(this,arguments)}w(a,b);a.prototype.create=function(){};return a}(Phaser.State),sa=function(){function b(a){this.Pa=a}b.prototype.find=function(a,b,c){var d=new FastPriorityQueue(function(a,b){return a.priority<b.priority});d.add(new R(a,0));var g={},l={};g[a]=null;l[a]=0;for(var p,t,x,H;!d.isEmpty();){p=d.pop().id;if(p==b)break;H=this.Pa.Hf(p,c);for(var ra in H)if(t=H[ra],x=l[p]+this.Pa.Db(p,t),void 0===l[t]||x<l[t])l[t]=x,x+=this.Pa.Ec(b,t),
d.add(new R(t,x)),g[t]=p}return void 0!==g[b]?this.kg(g,a,b):null};b.prototype.kg=function(a,b,c){for(var d=[c];c!=b;)c=a[c],d.push(c);d.reverse();return d};return b}();function R(b,a){this.id=b;this.priority=a}
var Map=function(){function b(){this.Ub=20;this.ab=15;this.vd=11;this.center=this.pa=null;this.Rc=[];this.Jf=h.add.graphics(0,0);this.Jc=h.add.graphics(0,0);this.ub=h.add.graphics(0,0);this.ub.visible=!1;this.elements=h.add.group();this.elements.add(this.Jf);this.elements.add(this.Jc);this.elements.add(this.ub);this.Ve();this.We();this.zc();this.df()}b.prototype.Ve=function(){var a;a=(this.vd+1)/2;a=h.world.height/(2*a+(this.vd-a));var b,c;b=(this.ab+1)/2;c=2*b+(this.ab-b);A.init(a);b=a*Math.sqrt(3)/
2;var d,g;d=2*b*this.Ub;g=c*a;c=new Phaser.Point;c.x=(h.world.width-d)/2+b;c.y=(h.world.height-g)/2+a;d=ta.Be;g=new S(a,a);this.ua=new ua(d,g,c);this.cells=[];var l;for(d=c=0;d<this.ab;d++){g=Math.floor(d/2);for(var p=-g;p<this.Ub-g;p++)l=new T(p,d,-p-d),l=new A(c,this,l,this.ua,a,b),this.cells.push(l),c++}this.Ac();this.Fd()};b.prototype.zc=function(){this.Jc.clear();for(var a in this.cells)this.cells[a].hb&&this.cells[a].draw(this.Jc)};b.prototype.df=function(){var a=this.cells[0].na.clone();a.Of();
this.cells[0].draw(this.ub,!0,a)};b.prototype.Ac=function(){var a=Math.floor((this.ab-1)/2),a=new T(Math.floor((this.Ub-1)/2)-Math.floor(a/2),a);this.center=this.Ia(a)};b.prototype.Fd=function(){this.Rc=[];for(var a,b,c,d=0;d<this.ab;d++){b=Math.floor(d/2);a=this.Ub-b-1;for(var g=-b;g<=a;g++)if(0==d||d==this.ab-1||g==-b||g==a)c=this.Ia(new T(g,d)),this.Rc.push(c)}};b.prototype.Df=function(){var a=f.shuffle(f.clone(this.cells)),b,c;for(c in a)if(b=a[c],null!=b&&b.Ib())return b;return null};b.prototype.Hc=
function(a,b,c,d){void 0===d&&(d=!1);var g=[];a=a.ha.Md(b);for(var l in a)b=this.Ia(a[l]),null==b||c&&!b.Ib()||d&&b.hb||g.push(b);return g};b.prototype.Cf=function(){var a=f.shuffle(this.Rc.slice()),b;for(b in a)if(a[b].Ib())return a[b];return null};b.prototype.pc=function(a){a=a.ha.neighbors();var b=[],c,d;for(d in a)c=this.Ia(a[d]),null!=c&&b.push(c);return b};b.prototype.We=function(){this.Kb=new va(this.cells.length);for(var a in this.cells)this.Xa(this.Kb,this.cells[a])};b.prototype.Xa=function(a,
b){var c;void 0===c&&(c=!1);var d,g;d=this.pc(b);for(var l in d)g=d[l],a.dc(b.id,g.id,1),c&&a.dc(g.id,b.id,1)};b.prototype.Ec=function(a,b){var c=this.ga(a);v(null!=c,"cellA with id '"+a+"' not found in cells, at getHeuristicDistance");var d=this.ga(b);v(null!=d,"cellA with id '"+b+"' not found in cells, at getHeuristicDistance");return c.ha.distance(d.ha)};b.prototype.ga=function(a){return this.cells[a]};b.prototype.ud=function(a){var b=[],c;for(c in a)b.push(this.ga(a[c]));return b};b.prototype.Ia=
function(a){for(var b in this.cells)if(this.cells[b].ha.kf(a))return this.cells[b];return null};b.prototype.uf=function(a){var b=[],c;for(c in this.cells)this.cells[c].vc(a)&&b.push(this.cells[c]);return b};b.prototype.vg=function(a){if(0<a.length){for(var b in a)a[b].ne(!1);this.zc()}};b.prototype.wg=function(a,b){var c=a.Kd(2,b),d,g;for(g in c)d=this.Ia(c[g]),null!=d&&d.ne(!0);this.zc()};b.prototype.xg=function(a){a=this.Tb(a);a!=this.pa&&(null!=this.pa&&(this.pa.Ta(!1),this.pa=null),null!=a&&a.hb&&
(a.Ta(!0),this.pa=a));return this.pa};b.prototype.Tb=function(a){var b=null;a=U.Yf(this.ua,a);null!=a&&(b=this.Ia(a));return b};b.prototype.Sf=function(a){a.Lc()&&this.ub.position.setTo(a.na.center.x,a.na.center.y);this.ub.visible=a.Lc()};return b}();function S(b,a){this.x=b;this.y=a}
var w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},wa=function(b){function a(a,c,d,g){b.call(this);this.level=a;this.controller=c;this.gameManager=d;this.o=g;this.Pc=!1;this.x=h.world.width-z.spacing;this.y=z.spacing;this.re=this.qb("button_swallow",1,21,this.$c,this,!1);this.ee=this.qb("button_plant",1,21,this.plant,this,!1);this.we=this.qb("button_watering",1,21,
this.fd,this,!1);this.buttons=[this.re,this.ee,this.we]}w(a,b);a.prototype.update=function(){var a=this.level.selection,b=this.o,d=!1,g=!1,l=!1;this.Pc||(this.gameManager.playing&&null!=a&&(a instanceof G&&!b.yb&&b.tb()?d=!0:a instanceof F&&a.alive&&b.tb()?d=!0:a instanceof E&&(a.ca>E.Ha.WATERED&&b.tb()&&(d=!0),a.ca==E.Ha.SEED&&b.Qe()&&(g=!0))),l=b.qc());this.re.Xc(d);this.ee.Xc(l);this.we.Xc(g)};a.prototype.$c=function(){this.controller.$c()};a.prototype.plant=function(){this.controller.plant()};
a.prototype.fd=function(){this.controller.fd()};return a}(z),va=function(){function b(a){void 0===a&&(a=0);this.nodes=[];for(var b=0;b<a;b++)this.Pf(b)}b.prototype.Pf=function(a){this.nodes.push(new fa(a))};b.prototype.He=function(a){this.nodes.push(a)};b.prototype.dc=function(a,b,c){var d=this.Yb(a);v(null!=d,"Can't find NetNode with id '"+a+"' when creating new link");a=this.Yb(b);v(null!=a,"Can't find NetNode with id '"+b+"' when creating new link");d.dc(a,c)};b.prototype.Gc=function(a){var b=
this.Yb(a);v(null!=b,"Can't find NetNode with id '"+a+"' when getting neighbors");return b.Gc()};b.prototype.Db=function(a,b){var c=this.Yb(a);v(null!=c,"Can't find NetNode with id '"+a+"' when getting cost");return c.Db(b)};b.prototype.Yb=function(a){return this.nodes[a]};b.prototype.clone=function(){var a=new b,e;for(e in this.nodes)a.He(this.nodes[e].clone());return a};return b}(),ua=function(){function b(a,b,c){this.orientation=a;this.size=b;this.origin=c}b.prototype.Kf=function(a){a=2*Math.PI*
(a+this.orientation.startAngle)/6;return new Phaser.Point(this.size.x*Math.cos(a),this.size.y*Math.sin(a))};b.prototype.bg=function(a){var b=[];a=U.Qd(this,a);for(var c,d=0;6>d;d++)c=this.Kf(d),b.push(new Phaser.Point(a.x+c.x,a.y+c.y));return b};return b}(),xa=function(){function b(a,b,c,d){this.level=a;this.map=b;this.controller=c;this.Mb=[];a=b.Hc(d.aa,Math.ceil(d.zg/2),!0,!0);this.Xf=new pa(b,c,a[f.Da(0,a.length,!0)])}b.prototype.wc=function(a){a=new E(this.level,this.map,this.controller,a);this.Mb.push(a);
return a};b.prototype.wf=function(a){var b=null,c,d=0,g=a.aa.ha,l=a.Zf,p;for(p in this.Mb)a=this.Mb[p],a.alive&&a.Ud()&&(c=g.distance(a.aa.ha),c<=l&&(null==b||c<d)&&(b=a,d=c));return b};return b}(),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},ya=function(b){function a(){b.apply(this,arguments)}w(a,b);a.prototype.create=function(){new y(y.ma.IMAGE,"button_back",z.spacing,
z.spacing,14,this.back,this);var a=h.add.text(h.world.centerX,z.spacing,n.about.title_text,{font:"bold "+z.fa(12)+"px Arial",fill:"#471c07"});a.anchor.setTo(.5,0);z.ra(a,12);h.add.text(h.world.centerX,a.y+a.height+z.spacing,n.about.description_text,{font:"bold "+z.fa(6)+"px Arial",fill:"#000000",wordWrap:!0,wordWrapWidth:z.Pb(90)}).anchor.setTo(.5,0);h.add.text(h.world.width-z.spacing,h.world.height-z.spacing,n.about.version_text+" "+m.about.version_number,{font:"bold "+z.fa(5)+"px Arial",fill:"#000000"}).anchor.setTo(1,
1)};a.prototype.back=function(){f.va("Menu")};return a}(Phaser.State),V=function(){function b(a,b,c,d,g){this.level=a;this.elements=b;this.Gg=c;this.percent=d;this.hc=g;this.Yc=!1;this.Zd=0;this.oe=700;this.Ga=0;this.Og=z.Pb(8);g.text=c;this.cd=this.ob=null;this.refresh();this.Sb=[];this.zd(4);h.time.events.loop(this.oe,this.show,this)}b.init=function(){var a=z.fa(5);b.ga={font:"bold "+a+"px Arial",fill:"#00a600"};b.ua={font:"bold "+a+"px Arial",fill:"#ff7800"}};b.prototype.refresh=function(){var a=
this.hc.position.y-this.hc.height/2;this.ob=new Phaser.Point(this.hc.position.x+this.hc.width,a);this.cd=new Phaser.Point(this.ob.x+this.Og,a)};b.prototype.Se=function(a){this.Ga+=a;this.show()};b.prototype.zd=function(a){for(var e=0;e<a;e++){var c=h.add.text(0,0,"",b.ga);c.anchor.setTo(0,.5);this.Sb.push(c);this.elements.add(c)}this.level.Nb()};b.prototype.show=function(){if(0!=this.Ga&&!this.Yc){this.Yc=!0;var a=Date.now();if(a-this.Zd>this.oe){0==this.Sb.length&&this.zd(3);var e=this.Sb.pop();
e.text=""+(0>this.Ga?this.Ga:"+"+this.Ga);e.setStyle(0>this.Ga?b.ua:b.ga);e.x=this.ob.x;e.y=this.ob.y;e.position.x=this.ob.x;e.position.y=this.ob.y;var c=h.add.tween(e).to({x:this.cd.x,y:this.cd.y},2E3,Phaser.Easing.Exponential.InOut);c.onStart.addOnce(function(a){a.alpha=1},this,0,e);var d=h.add.tween(e).to({alpha:0},300,Phaser.Easing.Linear.None);d.onComplete.addOnce(this.tg,this,0,e);c.chain(d);c.start();this.Ga=0;this.Zd=a}this.Yc=!1}};b.prototype.tg=function(a){a.alpha=0;this.Sb.push(a)};b.ga=
{};b.ua={};return b}(),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},za=function(b){function a(){b.call(this);this.x=h.world.centerX;this.y=h.world.centerY;this.Jd=h.add.text(z.spacing,0,n.menuinterface.gamename,{font:"bold "+z.fa(17)+"px Arial",fill:"#471c07"});this.Jd.anchor.setTo(0,0);z.ra(this.Jd,17);this.image=f.addSprite(0,h.world.height,"menu_image");this.image.anchor.setTo(0,
1);z.ra(this.image,83);this.qd=new y(y.ma.TEXT,String(n.menuinterface.play),this.x,this.y,22,this.play,this);this.sb=new y(y.ma.TEXT,String(n.menuinterface.scores),this.x,this.y,15,this.pg,this);this.pd=new y(y.ma.TEXT,String(n.menuinterface.about),this.x,this.y,15,this.De,this);this.qd.Sa(.5,1);this.sb.Sa(.5,.5);this.pd.Sa(.5,0);this.qd.moveTo(null,this.sb.y-z.spacing-this.sb.height/2);this.pd.moveTo(null,this.sb.y+z.spacing+this.sb.height/2)}w(a,b);a.prototype.play=function(){f.va("Level",!0)};
a.prototype.pg=function(){f.va("Scores")};a.prototype.De=function(){f.va("About")};return a}(z),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},Aa=function(b){function a(a,c){b.call(this);this.level=a;this.gameManager=c;this.y=this.x=z.spacing;this.qb("button_menu",0,14,this.gg,this);this.qb("button_restart",0,14,this.ng,this);this.ke=new B(a,c,n.gameinterface.dialog_quit,
this.fg,function(){},this);this.le=new B(a,c,n.gameinterface.dialog_restart,this.mg,function(){},this);this.Dd=h.add.group();var d=this.le.elements.concat(this.ke.elements),g;for(g in d)this.Dd.add(d[g])}w(a,b);a.prototype.gg=function(){this.gameManager.playing?this.ke.show():this.level.je()};a.prototype.ng=function(){this.gameManager.playing?this.le.show():this.level.restart()};a.prototype.fg=function(){this.level.je()};a.prototype.mg=function(){this.level.restart()};return a}(z),w=this&&this.la||
function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},G=function(b){function a(a,c,d){b.call(this,a,c,d,m.waterpoint.sizecells,m.waterpoint.sizesprite,"waterhole",!0,!0,!0);this.group.rotation=f.Zb()}w(a,b);return a}(Entity);function Ba(){}
var A=function(){function b(a,b,c,d,g){this.id=a;this.map=b;this.ha=c;this.edge=g;this.selected=this.hb=!1;this.entities=[];this.na=new Ca(c,d);this.$b=this.polygon=new Phaser.Polygon(this.na.ka)}b.init=function(a){b.pb=a;b.Ae=2*a;a=z.fa(.5);b.ga[0]=a;b.ua[0]=a;b.Xa[0]=z.fa(.7)};b.prototype.draw=function(a,e,c){void 0===e&&(e=!1);void 0===c&&(c=this.na);e=e?b.Xa:this.hb?b.ua:b.ga;a.lineStyle(e[0],e[1],e[2]);a.drawPolygon(c.ka);a.lineTo(c.$a.x,c.$a.y);a.endFill()};b.prototype.clear=function(a){a.beginFill(16777215,
1);a.drawPolygon(this.na.ka);a.lineTo(this.na.$a.x,this.na.$a.y);a.endFill()};b.prototype.Lc=function(){return this.selected};b.prototype.ne=function(a){this.hb=a};b.prototype.Ta=function(a){this.selected=a&&this.hb?!0:!1;this.map.Sf(this)};b.prototype.mc=function(a){this.vc(a)||this.entities.push(a)};b.prototype.vc=function(a){for(var b in this.entities)if(this.entities[b]==a)return!0;return!1};b.prototype.gc=function(a){for(var b in this.entities)if(this.entities[b]==a){this.entities.splice(parseInt(b),
1);break}};b.prototype.isEmpty=function(){return 0==this.entities.length};b.prototype.Bf=function(){var a=null,b,c;for(c in this.entities)if(b=this.entities[c],null==a||b instanceof F)a=b;return a};b.prototype.Ib=function(){return this.isEmpty()||!this.Ue()};b.prototype.Ue=function(){for(var a in this.entities)if(!this.entities[a].Pg)return!0;return!1};b.prototype.Fc=function(){return this.$b};b.prototype.toString=function(){return this.ha.toString()};b.Ac=16734003;b.ga=[5,8421504,.7];b.ua=[5,6710886,
.7];b.Xa=[5,16777215,1];return b}(),T=function(){function b(a,b,c){this.x=a;this.y=b;this.z=c;void 0===c&&(this.z=c=-a-b);v(0==a+b+c,"Hex invalid for x="+a+", y="+b+", z="+c)}b.prototype.kf=function(a){return this.x==a.x&&this.y==a.y&&this.z==a.z};b.prototype.add=function(a){return new b(this.x+a.x,this.y+a.y,this.z+a.z)};b.prototype.subtract=function(a){return new b(this.x-a.x,this.y-a.y,this.z-a.z)};b.prototype.multiply=function(a){return new b(this.x*a,this.y*a,this.z*a)};b.prototype.length=function(){return Math.floor((Math.abs(this.x)+
Math.abs(this.y)+Math.abs(this.z))/2)};b.prototype.distance=function(a){return this.subtract(a).length()};b.direction=function(a){v(0<=a&&6>a,"Hex direction should be between 0 and 5 included, actual is "+a);return b.ga[a]};b.prototype.be=function(a){return this.add(b.direction(a))};b.prototype.neighbors=function(){for(var a=[],e=0;e<b.ga.length;e++)a.push(this.be(e));return a};b.prototype.round=function(){var a=Math.round(this.x),b=Math.round(this.y),c=Math.round(this.z),d=Math.abs(a-this.x),g=Math.abs(b-
this.y),l=Math.abs(c-this.z);d>g&&d>l?a=-b-c:g>l?b=-a-c:c=-a-b;this.x=a;this.y=b;this.z=c};b.prototype.Md=function(a){for(var e=this,c=0;c<a;c++)e=e.add(b.direction(4));for(var c=[],d=0;6>d;d++)for(var g=0;g<a;g++)c.push(e),e=e.be(d);return c};b.prototype.Kd=function(a,b){for(var c=[],d=a;d<=b;d++)c=c.concat(this.Md(d));return c};b.prototype.toString=function(){return"["+this.x+", "+this.y+"]"};b.ga=[new b(1,0,-1),new b(1,-1,0),new b(0,-1,1),new b(-1,0,1),new b(-1,1,0),new b(0,1,-1)];return b}(),
Q=function(){function b(){}b.init=function(){var a=h.add.graphics(0,0);a.beginFill(0,1);a.drawRect(0,0,h.world.width,h.world.height);a.endFill();var e=h.add.text(h.world.centerX,h.world.centerY,n.loadingscreen.title,{font:"bold "+z.fa(20)+"px Arial",fill:"#FFFFFF"});e.anchor.setTo(.5,.5);z.ra(e,20);b.group=h.add.group();b.group.add(a);b.group.add(e);b.hide()};b.hide=function(){b.group.visible=!1};b.show=function(){b.group.visible=!0;h.world.bringToTop(b.group)};return b}(),ea=function(){function b(a,
b,c){this.Rf=a;this.Nc=b;this.weight=c}b.prototype.clone=function(){return new b(this.Rf,this.Nc,this.weight)};return b}(),U=function(){function b(){}b.Qd=function(a,b){var c=a.orientation;return new Phaser.Point((c.lf*b.x+c.mf*b.y)*a.size.x+a.origin.x,(c.nf*b.x+c.pf*b.y)*a.size.y+a.origin.y)};b.Yf=function(a,b){var c=a.orientation,d=new S((b.x-a.origin.x)/a.size.x,(b.y-a.origin.y)/a.size.y),g=c.Le*d.x+c.Me*d.y,c=c.Ne*d.x+c.Oe*d.y,g=new T(g,c,-g-c);g.round();return g};b.ga=function(a,b,c){return a*
(1-c)+b*c};b.ua=function(a,e,c){return new T(b.ga(a.x,e.x,c),b.ga(a.y,e.y,c),b.ga(a.z,e.z,c))};b.Fd=function(a,e){for(var c=a.distance(e),d=[],g=1/Math.max(c,1),l=0;l<=c;l++)d.push(b.ua(a,e,g*l));return d};return b}(),ia=function(){function b(a){this.map=a;this.Kb=this.map.Kb;this.Ke=new sa(this)}b.prototype.find=function(a,b,c){var d=[];if(void 0!==c){c=this.map.uf(c);for(var g in c)d.push(c[g].id)}a=this.Ke.find(a.id,b.id,d);return null!=a?this.map.ud(a):null};b.prototype.Hf=function(a,b){var c=
this.map.ud(this.Kb.Gc(a)),d=[],g,l;for(l in c)g=c[l],(g.Ib()||f.inArray(b,g.id))&&d.push(g.id);return d};b.prototype.Db=function(a,b){return this.Kb.Db(a,b)};b.prototype.Ec=function(a,b){return this.map.Ec(a,b)};return b}(),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},Fa=function(b){function a(){b.apply(this,arguments);this.Td=!1;this.selection=null}w(a,b);a.prototype.create=
function(){h.physics.startSystem(Phaser.Physics.ARCADE);this.controller=new ka(this);this.map=new Map;this.gameManager=new Da(this.controller);this.j=new ja(this,this.map,this.controller);this.Sd=new Ea(this.map,this.controller,this.j.o);this.qa=new xa(this,this.map,this.controller,this.Sd.ze);new Ba;this.Bb=new Aa(this,this.gameManager);this.Ka=new I(this,this.gameManager,this.j.o);this.xa=new wa(this,this.controller,this.gameManager,this.j.o);this.Xb=new na(this,this.controller,this.map,this.gameManager,
this.Bb,this.xa);this.controller.init(this.gameManager,this.qa,this.j,this.Ka);this.gameManager.init(this.Ka);this.j.init(this.qa);this.sounds=new D("level");this.Td=!0;Q.hide();this.start()};a.prototype.start=function(){this.j.start();this.gameManager.start();this.xa.update();this.Nb();this.sounds.play("startgame")};a.prototype.restart=function(){this.gameManager.end();this.j.end();f.va("Level",!0)};a.prototype.je=function(){this.gameManager.end();this.j.end();f.va("Menu")};a.prototype.update=function(){this.gameManager.isPaused||
(h.input.activePointer.isDown&&!this.Xb.Gb&&this.Xb.Oc?(this.j.o.alive&&(this.j.o.rotation=h.physics.arcade.angleToPointer(this.j.o.group)),null==this.selection||!this.Xb.isDragging&&this.Xb.de||this.controller.ve()):null!=this.selection&&this.j.o.alive&&(this.j.o.rotation=f.Dc(this.j.o.group,this.selection instanceof Entity?this.selection.group.position:this.selection.na.center)),this.j.update(),this.xa.update())};a.prototype.render=function(){};a.prototype.Nb=function(){if(this.Td){var a=[];a.push(this.map.elements);
a.push(this.Sd.ze.group);for(var b in this.qa.Mb)a.push(this.qa.Mb[b].group);for(b in this.j.Ba)a.push(this.j.Ba[b].group);a.push(this.qa.Xf.group);this.j.o.Ob.lc&&a.push(this.j.o.Ob.eb);a.push(this.j.o.wa);a.push(this.j.o.seed);a.push(this.j.o.group);a.push(this.Bb.elements);a.push(this.Ka.elements);a.push(this.xa.elements);a.push(this.gameManager.ec);a.push(this.gameManager.Qa);a.push(this.gameManager.Ab);a.push(this.gameManager.Za);a.push(this.Bb.Dd);for(b in a)h.world.bringToTop(a[b])}};a.prototype.select=
function(a){a instanceof A&&!a.isEmpty()?(a.Ta(!1),this.select(a.Bf())):(this.selection!=a&&(null!=this.selection&&this.selection.Ta(!1),null!=a&&(a.Ta(!0),this.sounds.play("select_entity")),this.j.o.yg(a),this.selection=a),this.xa.update(),this.Nb())};return a}(Phaser.State),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},F=function(b){function a(a,c,d,g,l,p,t){b.call(this,
c,d,p,m.prey.sizecells,m.prey.sizesprite,"prey",!1,!0,!0);this.level=a;this.j=g;this.zb=null;this.isMoving=!1;this.Na=[];this.Mc=!1;this.Aa=this.Ea=null;this.Ma=!0;this.Wb=this.Lb=!1;this.ia=null;this.freeze=!1;this.rb=null;this.volume=1;this.speed=m.prey.speed_normal;this.Dg=m.prey.speed_sprint;this.Zf=m.prey.plant_detectiondistance;this.Hg=Phaser.Timer.SECOND/m.prey.think_persecond;this.hf=m.prey.eat_time;this.Te=m.prey.chewtime;this.sounds=new D("prey");this.Cg=m.prey.sound_distancemax;this.kill();
this.sprite.animations.add("chew",null,Math.ceil(1E3/(this.Te/6)),!0);this.nc=new ma(a,c,g,l,this,t)}w(a,b);a.prototype.update=function(){if(this.alive){var a=1-Math.min(1,1*this.aa.ha.distance(this.j.o.aa.ha)/this.Cg);.01<=Math.abs(this.volume-a)&&(this.volume=a,this.sounds.volume("creature_walk",this.volume),this.sounds.volume("creature_sprint",this.volume),this.sounds.volume("eat_plant",this.volume),this.sounds.volume("prey_scared",this.volume))}};a.prototype.kill=function(){null!=this.rb&&(this.rb.timer.remove(this.rb),
this.rb=null);this.jb(!0);this.Ua();null!=this.aa&&(this.aa.gc(this),this.aa=null);null!=this.Aa&&(this.Aa.gc(this),this.Aa=null);this.group.alpha=0;this.destroy();this.sounds.stopAll()};a.prototype.jg=function(){this.group.alpha=1;this.isMoving=this.freeze=!1;this.Zc();this.Ma=!0;this.Lb=!1;this.nc.init();this.rb=h.time.events.loop(this.Hg,this.kb,this);this.kb();this.level.Nb()};a.prototype.tf=function(a,b){null!=a&&0<a.length&&(this.jb(),this.Ua(),this.isMoving=!0,this.Na=a,this.Mc=b,this.Lb=!this.Ma,
this.Na.shift(),this.ae(),this.Mc?this.sounds.play("creature_sprint"):this.sounds.play("creature_walk"))};a.prototype.ae=function(){this.Ma&&(0<this.Na.length?this.Nf(this.Na[0],this.Mc):this.Uf())};a.prototype.Nf=function(a,b){var d=a.na.center;this.group.rotation=f.Dc(this.group,d);if(a.Ib()){this.Aa=a;this.Aa.mc(this);var g=1E3/(b?this.Dg:this.speed);this.Ea=h.add.tween(this.group).to({x:d.x,y:d.y},g);this.Ea.onComplete.add(this.onMoveComplete,this);this.Ea.start();this.Ma=!1}else this.jb()};a.prototype.onMoveComplete=
function(){this.Ma||(this.aa.gc(this),this.aa=this.Aa,this.aa.mc(this),this.Ea=this.Aa=null,this.Ma=!0,0<this.Na.length&&!this.Lb&&this.Na.shift(),this.Lb=!1,this.ae())};a.prototype.Uf=function(){this.jb();this.Ua();this.Lb=!1;this.sounds.stop("creature_sprint");this.sounds.stop("creature_walk");this.nc.kb()};a.prototype.jb=function(a){void 0===a&&(a=!1);this.isMoving&&(null!=this.Ea&&a&&(this.Ea.stop(!1),h.tweens.remove(this.Ea),this.Ea=null),this.isMoving=!1,this.Na=[],this.kb())};a.prototype.kb=
function(){this.freeze||this.nc.kb()};a.prototype.Vd=function(a){return this.aa==a.aa&&this.Ma};a.prototype.Bc=function(a){a instanceof E&&a.Ud()&&(this.jb(),this.Ua(),this.Wb=!0,this.sprite.animations.play("chew"),this.ia=a,this.zb=h.time.events.loop(this.hf,this.gf,this),this.sounds.play("eat_plant"))};a.prototype.gf=function(){null!=this.ia&&this.ia.alive?this.ia.cf():this.Ua()};a.prototype.Ua=function(){this.Wb&&(this.Wb=!1,null!=this.zb&&(this.sprite.animations.stop(null,!0),this.zb.timer.remove(this.zb),
this.zb=null),this.sounds.stop("eat_plant"))};a.prototype.qf=function(){this.sounds.play("prey_scared")};return a}(Entity),W,X=W||(W={});X[X.TEXT=0]="TEXT";X[X.IMAGE=1]="IMAGE";
var y=function(){function b(a,e,c,d,g,l,p,t,x){void 0===t&&(t=!0);void 0===x&&(x=3574271);this.type=a;this.x=c;this.y=d;this.callback=l;this.context=p;this.Lf=t;this.nd=this.md=0;this.uc=!0;l=z.fa(1);this.padding=l+z.fa(1);g-=4;a==b.ma.TEXT&&(this.text=h.add.text(this.padding,this.padding,e,{font:"bold "+z.fa(g)+"px Arial",fill:"#000000"}));a==b.ma.IMAGE&&(this.image=f.addSprite(this.padding,this.padding,e,t));this.element=a==b.ma.TEXT?this.text:this.image;z.ra(this.element,g);this.width=this.element.width+
2*this.padding;this.height=this.element.height+2*this.padding;this.og=z.fa(4);this.Eb=this.Ld(x,l,16770560);this.Ic=this.Ld(8421504,l,0);this.Ic.visible=!1;this.scale=new Phaser.Point(1,1);this.Wc=new Phaser.Point(.8,.8);this.Eb.inputEnabled=!0;this.Eb.events.onInputDown.add(this.onInputDown,this);this.Eb.events.onInputUp.add(this.onInputUp,this);this.group=h.add.group();this.group.add(this.Ic);this.group.add(this.Eb);this.group.add(a==b.ma.TEXT?this.element:this.image);this.moveTo(c,d)}b.prototype.Ld=
function(a,b,c){var d=h.add.graphics(0,0);d.beginFill(a);d.lineStyle(b,c,1);d.drawRoundedRect(0,0,this.width,this.height,this.og);return d};b.prototype.Sa=function(a,b){this.md=a;this.nd=b;this.moveTo(this.x,this.y)};b.prototype.moveTo=function(a,b){null!==a&&(this.x=a,this.hd=this.x-this.width*this.md,this.group.x=this.hd);null!==b&&(this.y=b,this.jd=this.y-this.height*this.nd,this.group.y=this.jd);this.Tg=this.hd+(this.width-this.width*this.Wc.x)/2;this.Vg=this.jd+(this.height-this.height*this.Wc.y)/
2};b.prototype.onInputDown=function(){this.uc&&(u.play("menu_selection"),this.group.scale=this.Wc,this.group.x=this.Tg,this.group.y=this.Vg)};b.prototype.onInputUp=function(){this.uc&&(this.group.scale=this.scale,this.group.x=this.hd,this.group.y=this.jd,this.callback.apply(this.context))};b.prototype.Xc=function(a){this.uc=a;this.type!=b.ma.IMAGE||this.Lf||(this.image.frame=a?0:1);this.Eb.visible=a;this.Ic.visible=!a};b.ma=W;return b}();
function Ea(b,a,e){e=b.Hc(e.aa,m.inertmanager.oasisdistance,!1);this.ze=new G(b,a,e[f.Da(0,e.length,!0)])}
var Ca=function(){function b(a,b){if(void 0!==a){var c=U.Qd(b,a);this.center=new Phaser.Point(c.x,c.y);this.ka=b.bg(a);this.ue=this.ka[4];this.$a=this.ka[0]}}b.prototype.Of=function(){var a,b,c;a=-this.center.x;b=-this.center.y;for(var d in this.ka)c=this.ka[d],c.x+=a,c.y+=b;this.center.setTo(0,0);this.ue=this.ka[4];this.$a=this.ka[0]};b.prototype.clone=function(){var a=new b;a.center=this.center.clone();a.ka=[];for(var e in this.ka)a.ka.push(this.ka[e].clone());a.ue=a.ka[4];a.$a=a.ka[0];return a};
b.prototype.toString=function(){return"center: "+this.center+", corners: "+this.ka};return b}(),Da=function(){function b(a){this.controller=a;this.playing=!1;this.Fa=0;this.isPaused=!1;this.Uc=null;this.ig=Phaser.Timer.SECOND*m.gamemanager.raisescoretime;this.Jb=15;a=z.fa(this.Jb);this.ec=h.add.text(h.world.centerX,z.spacing,n.gamemanager.objective_text,{font:"bold "+a+"px Arial",fill:"#B30065"});this.ec.anchor.setTo(.5,0);z.ra(this.ec,this.Jb);this.Qa=h.add.text(h.world.centerX,z.spacing,"",{font:"bold "+
a+"px Arial",fill:"#ccff33"});this.Qa.anchor.setTo(.5,0);this.Qa.visible=!1;this.Za=h.add.text(h.world.centerX,h.world.centerY/2+z.spacing,n.gamemanager.bestscore_text,{font:"bold "+a+"px Arial",fill:"#EFD807"});this.Za.anchor.setTo(.5,.5);this.oc=this.Za.visible=!1;z.ra(this.Za,this.Jb);this.Ab=h.add.text(h.world.centerX,h.world.centerY+z.spacing,n.gamemanager.endgame_text,{font:"bold "+a+"px Arial",fill:"#e6e6e6"});this.Ab.anchor.setTo(.5,0);this.Ab.visible=!1;z.ra(this.Ab,this.Jb);this.sounds=
new D("gamemanager")}b.prototype.init=function(a){this.Ka=a};b.prototype.start=function(){this.Uc=h.time.events.loop(this.ig,this.hg,this);h.time.events.add(3*Phaser.Timer.SECOND,function(){h.add.tween(this.ec).to({alpha:0},1E3,Phaser.Easing.Linear.None,!0)},this);this.Qa.visible=!1;this.oc=this.Za.visible=!1;this.playing=!0};b.prototype.end=function(){this.playing&&(this.Uc.timer.remove(this.Uc),this.controller.ve(),this.playing=!1,this.Qa.setText(n.gamemanager.score+this.Fa),this.Qa.visible=!0,
z.ra(this.Qa,this.Jb),this.Ab.visible=!0,this.Ie(),this.oc?(this.Za.visible=!0,this.sounds.play("endgame_bestscore")):this.sounds.play("endgame"))};b.prototype.hg=function(){this.Fa+=1;this.Ka.update(I.Wa.SCORE,this.Fa,1)};b.prototype.Ie=function(){this.playing||(0<r.Ca&&this.Fa>r.Ca&&(this.oc=!0),r.add(this.Fa))};return b}(),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,
new e)},Ga=function(b){function a(){b.apply(this,arguments)}w(a,b);a.prototype.create=function(){new za;Q.hide()};return a}(Phaser.State),w=this&&this.la||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},Y,Z=Y||(Y={});Z[Z.SEEDS=0]="SEEDS";Z[Z.ENERGY=1]="ENERGY";Z[Z.HUNGER=2]="HUNGER";Z[Z.HYDRATION=3]="HYDRATION";Z[Z.HEALTH=4]="HEALTH";Z[Z.SCORE=5]="SCORE";
var I=function(b){function a(a,c,d){b.call(this);this.level=a;this.y=h.world.height-z.spacing;this.style={font:"bold "+z.fa(5)+"px Arial",fill:"#2b6dcc"};this.ja=[];for(var g=0;6>g;g++)this.ja[g]=this.addText();this.ta=[];this.ta[Y.SCORE]=new V(a,this.elements,n.gamestateinterface.score,!1,this.ja[Y.SCORE]);this.ta[Y.HEALTH]=new V(a,this.elements,n.gamestateinterface.health,!0,this.ja[Y.HEALTH]);this.ta[Y.HYDRATION]=new V(a,this.elements,n.gamestateinterface.hydration,!0,this.ja[Y.HYDRATION]);this.ta[Y.HUNGER]=
new V(a,this.elements,n.gamestateinterface.hunger,!0,this.ja[Y.HUNGER]);this.ta[Y.ENERGY]=new V(a,this.elements,n.gamestateinterface.energy,!0,this.ja[Y.ENERGY]);this.ta[Y.SEEDS]=new V(a,this.elements,n.gamestateinterface.seeds,!1,this.ja[Y.SEEDS]);this.init(c,d)}w(a,b);a.prototype.init=function(a,b){this.set(Y.SCORE,a.Fa);for(var d=0;d<this.ta.length;d++)this.set(d,10),this.ta[d].refresh();this.set(Y.SCORE,a.Fa);this.set(Y.HEALTH,b.health);this.set(Y.HYDRATION,b.za);this.set(Y.HUNGER,b.La);this.set(Y.ENERGY,
b.Ja);this.set(Y.SEEDS,b.Ra)};a.prototype.update=function(a,b,d){this.set(a,b);this.ta[a].Se(d)};a.prototype.addText=function(a){void 0===a&&(a="");0<this.ja.length&&(this.y-=this.ja[this.ja.length-1].height);a=h.add.text(z.spacing,this.y,a,this.style);a.anchor.setTo(0,1);this.elements.add(a);return a};a.prototype.set=function(a,b){var d=this.ta[a];this.ja[a].text=d.Gg+String(b)+(d.percent?n.gamestateinterface.percent:"")};a.Wa=Y;return a}(z),w=this&&this.la||function(b,a){function e(){this.constructor=
b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)},aa=function(b){function a(){b.apply(this,arguments)}w(a,b);a.prototype.preload=function(){h.stage.backgroundColor="#d3a548";h.load.pack("global","assets/assets-pack.json");h.load.pack("level","assets/assets-pack.json");h.load.pack("scores","assets/assets-pack.json");h.load.pack("about","assets/assets-pack.json")};a.prototype.create=function(){oa.init();z.init();V.init();D.init();
m=h.cache.getJSON("config_normal");m.global.inspector&&h.plugins.add(Phaser.Plugin.Inspector);q=n.global.player_name;new ha;u=new D("global");u.play("ambiance_desert");r=new ca;h.state.add("Menu",Ga);h.state.add("Level",Fa);h.state.add("Scores",ga);h.state.add("About",ya);h.state.add("Test",qa);f.va("Menu")};return a}(Phaser.State),ta=function(){function b(a,b,c,d,g,l,p,t,x){this.lf=a;this.mf=b;this.nf=c;this.pf=d;this.Le=g;this.Me=l;this.Ne=p;this.Oe=t;this.startAngle=x}b.Be=new b(Math.sqrt(3),Math.sqrt(3)/
2,0,1.5,Math.sqrt(3)/3,-1/3,0,2/3,.5);b.ga=new b(1.5,0,Math.sqrt(3)/2,Math.sqrt(3),2/3,0,-1/3,Math.sqrt(3)/3,0);return b}();
